direcciones_CHOICES ={
    "Principal urbano" : {
        "Circunvalar":"CV",
        "Kilómetro":"KM",
        "Autpista":"AU",
        "Avenida Calle":"AC",
        "Avenida Carrera":"AK",
        "Transversal":"TV",
        "Troncal":"TC",
        "Diagonal":"DG",
        "Variante":"VT",
        "Calle":"CL",
        "Vía":"VIA",
        "Camino":"CAM",
        "Viaducto":"VD",
        "Carrera":"KR",
        "Round point / Glorieta":"RP",
        "Carretera":"CT"
    },
    
    "Orientacion urbano" : {
        "Oriente":"E",
        "Sur":"S",
        "Sur Este/ Sur Oriente":"SE",
        "Sur Oeste/ Sur Occidente":"SO",
        "Norte":"N",
        "Nor Oeste / Nor Occidente":"NO",
        "Nor este / Nor Oriente":"NE",
        "Este / Oriente":"E",
        "Oeste / Occidente":"W"
    },

    "Bis urbano" : {
        "Bis":"BIS"
    },

    "Complemento urbano" : {
        "Apartamento":"AP",
        "Casa":"CA",
        "Lote":"LT",
        "Local":"LC",
        "Local Mezzanine":"LM",
        "Manzana":"MZ",
        "Piso":"PI",
        "Esquina":"EQ",
        "Edificio":"ED",
        "Bloque":"BQ",
        "Bodega":"BG",
        "Interior":"IN",
        "Administración":"AD",
        "Oficina":"OF",
        "Exterior":"EX",
        "Aeropuerto":"AE",
        "Sección":"SECC",
        "Célula":"CU",
        "Ferrocarril":"FFC",
        "Oficina Sótano":"OS",
        "Sector":"SECT",
        "Agencia":"AGN",
        "Centro comercial":"CC",
        "Agrupación":"AG",
        "Circular":"CQ",
        "Garaje":"GJ",
        "Paraje":"PRJ",
        "Almacén":"ALM",
        "Garaje Sótano":"GS",
        "Sótano":"ST",
        "Ciudadela":"DC",
        "Habitación":"HB",
        "Parque":"PQ",
        "Suite":"SU",
        "Apartado":"APTDP",
        "Condominio":"CM",
        "Parqueadero":"PA",
        "Supermanzana":"SM",
        "Conjunto / Conjunto Residencial":"CO",
        "Pasaje":"PJ",
        "Solar":"SL",
        "Apartamento Sótano":"AS",
        "Consultorio":"CN",
        "Paseo":"PS",
        "Contador":"CNT",
        "Peatonal":"PT",
        "Penthouse":"PH",
        "Terminal":"TER",
        "Avenida":"AV",
        "Cuarto":"QT",
        "Local sótano":"LS",
        "Terraza":"TZ",
        "Torre":"TO",
        "Departamento":"DPTO",
        "Planta":"PL",
        "Barrio":"BR",
        "Depósito":"DP",
        "Plaza":"PLZ",
        "Depósito Sótano":"DS",
        "Mezzanine":"MN",
        "Portería":"PR",
        "Unidad":"UN",
        "Descripción Adicional":"DA",
        "Módulo":"MD",
        "Predio":"PD",
        "Unidad Residencial / Urbanización":"UR",
        "Puente":"PTE",
        "Boulevard":"BL",
        "Nivel":"PI",
        "Puesto":"PU",
        "Quintas":"QNT",
        "Entrada":"EN",
        "Etapa":"ET",
        "Residencias":"RSD",
        "Estación":"ES",
        "Zona":"ZN",
        "Nucleo":"UN",
        "Salón":"SA",
        "Zona franca":"ZF",
        "Salón comunal":"SC"
    },
    
    "Principal rural" : {
        "Caserío":"CAS",
        "Corregimiento":"CRG",
        "Predio":"PD",
        "Unidad Residencial / Urbanización":"UR",
        "Vereda ":"VDA",
        "Vía":"VIA",
        "Camino":"CAM",
        "Carretera":"CT"
    },
    
    "Complemento rural" : {
        "Finca":"FI",
        "Parcela":"PAR",
        "Hacienda":"HC",
        "Kilómetro":"KM",
        "Lote":"LT",
        "Variante":"VT",
        "Entrada":"EN",
        "Quintas":"QNT",
        "Zona":"ZN"
    }
}