# Generated by Django 4.1.1 on 2022-09-29 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre_de_usuario', models.CharField(db_column='TznombreUsuario', max_length=100)),
                ('is_active', models.BooleanField(db_column='Tzactivo', default=False)),
                ('is_staff', models.BooleanField(db_column='Tzstaff', default=False)),
                ('is_superuser', models.BooleanField(db_column='TzsuperUser', default=False)),
                ('is_blocked', models.BooleanField(db_column='Tzbloqueado', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='TzfechaCreacion')),
                ('activated_at', models.DateTimeField(db_column='TzfechaActivacionInicial', null=True)),
                ('tipo_usuario', models.CharField(db_column='TztipoUsuario', max_length=50)),
                ('email', models.EmailField(db_column='TzemailUsuario', max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_usuario_creador', models.ForeignKey(db_column='TzId_Usuario_Creador', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'TzUsuarios',
            },
        ),
        migrations.CreateModel(
            name='ClasesTercero',
            fields=[
                ('id_tipo_tercero', models.AutoField(db_column='T007IdTipoTercero', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T007nombre', max_length=100)),
            ],
            options={
                'verbose_name': 'Clase tercero',
                'verbose_name_plural': 'Clase terceros',
                'db_table': 'T007ClasesTercero',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('nombre', models.CharField(db_column='T002nombre', max_length=30)),
                ('cod_departamento', models.CharField(db_column='T002CodDepartamento', max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'T002DepartamentosPais',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('nombre', models.CharField(db_column='T005nombre', max_length=20)),
                ('cod_estado_civil', models.CharField(db_column='T005CodEstadoCivil', max_length=1, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Estado civil',
                'verbose_name_plural': 'Estado civil',
                'db_table': 'T005EstadoCivil',
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_modulo', models.AutoField(db_column='TzIdModulo', editable=False, primary_key=True, serialize=False)),
                ('nombre_modulo', models.CharField(db_column='TznombreModulo', max_length=50)),
                ('subsistema', models.CharField(db_column='Tzsubsistema', max_length=50)),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'db_table': 'TzModulos',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='T001nombre', max_length=30)),
                ('cod_municipio', models.CharField(db_column='T001CodMunicipio', max_length=5)),
                ('cod_departamento', models.ForeignKey(blank=True, db_column='T001Cod_Departamentos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'T001MunicipiosDepartamento',
            },
        ),
        migrations.CreateModel(
            name='OperacionesSobreUsuario',
            fields=[
                ('cod_operacion', models.AutoField(db_column='T008CodOperacion', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T008nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Operacion sobre usuario',
                'verbose_name_plural': 'Operaciones sobre usuario',
                'db_table': 'T008OperacionesSobreUsusario',
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('nombre', models.CharField(db_column='T003nombre', max_length=50)),
                ('cod_pais', models.CharField(db_column='T003CodPais', max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'T003Paises',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('nombre_permiso', models.CharField(db_column='TznombrePermiso', max_length=50)),
                ('cod_permiso', models.AutoField(db_column='TzCodPermiso', editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'TzPermisos',
            },
        ),
        migrations.CreateModel(
            name='PermisosModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_permiso', models.ForeignKey(blank=True, db_column='TzCodPermiso', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.permisos')),
                ('id_modulo', models.ForeignKey(blank=True, db_column='TzIdModulo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.modulos')),
            ],
            options={
                'verbose_name': 'Permiso de módulo',
                'verbose_name_plural': 'Permisos de módulo',
                'db_table': 'TzPermisos_Modulo',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_persona', models.AutoField(db_column='T010IdPersona', editable=False, primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(db_column='T010tipoPersona', max_length=50)),
                ('numero_documento', models.CharField(db_column='T010nroDocumento', max_length=50, unique=True)),
                ('digito_verificacion', models.CharField(db_column='T010digitoVerificacion', max_length=50)),
                ('primer_nombre', models.CharField(db_column='T010primerNombre', max_length=50)),
                ('segundo_nombre', models.CharField(db_column='T010segundoNombre', max_length=50)),
                ('primer_apellido', models.CharField(db_column='T010primerApellido', max_length=50)),
                ('segundo_apellido', models.CharField(db_column='T010segundoApellido', max_length=50)),
                ('nombre_comercial', models.CharField(db_column='T010nombreComercial', max_length=50)),
                ('razon_social', models.CharField(db_column='T010razonSocial', max_length=255)),
                ('pais_residencia', models.CharField(db_column='T010codPaisResidencia', max_length=50)),
                ('direccion_residencia', models.CharField(db_column='T010direccionResidencia', max_length=50)),
                ('direccion_residencia_ref', models.CharField(db_column='T010direccionResidenciaRef', max_length=50)),
                ('ubicacion_georeferenciada', models.CharField(db_column='T010ubicacionGeoreferenciada', max_length=50)),
                ('direccion_laboral', models.CharField(db_column='T010direccionLaboral', max_length=50)),
                ('direccion_correspondencia', models.CharField(db_column='T010direccionCorrespondencia', max_length=50)),
                ('representate_legal', models.CharField(db_column='T010IdRepresentanteLegal', max_length=50)),
                ('email', models.EmailField(db_column='T010email', max_length=255, unique=True)),
                ('email_empresarial', models.EmailField(db_column='T010emailEmpresarial', max_length=255)),
                ('telefono_fijo_residencial', models.CharField(db_column='T010telFijoResidencial', max_length=10)),
                ('telefono_celular', models.CharField(db_column='T010telCelular', max_length=10)),
                ('telefono_empresa', models.CharField(db_column='T010telEmpresa', max_length=10)),
                ('estado_civil', models.ForeignKey(db_column='T010Cod_Estado_Civil', on_delete=django.db.models.deletion.CASCADE, to='seguridad.estadocivil')),
                ('municipio_residencia', models.ForeignKey(blank=True, db_column='T010Cod_MunicipioResidencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.municipio')),
                ('pais_nacimiento', models.ForeignKey(db_column='T010Cod_Pais_Nacimiento', on_delete=django.db.models.deletion.CASCADE, to='seguridad.paises')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'T010Personas',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(db_column='TzIdRol', editable=False, primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='TznombreRol', max_length=50)),
                ('descripcion_rol', models.CharField(db_column='TzdescripcionRol', max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'TzRoles',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('nombre', models.CharField(db_column='T004nombre', max_length=50)),
                ('cod_sexo', models.CharField(db_column='T004CodSexo', max_length=1, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexo',
                'db_table': 'T004Sexo',
            },
        ),
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('cod_tipo_documento', models.AutoField(db_column='T006CodTipoDocumento', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T006nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'db_table': 'T006TiposDocumento',
            },
        ),
        migrations.CreateModel(
            name='UsuariosRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.ForeignKey(blank=True, db_column='TzIdRol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.roles')),
                ('id_usuario', models.ForeignKey(db_column='TzIdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de usuario',
                'verbose_name_plural': 'Roles de usuario',
                'db_table': 'TzUsuarios_Rol',
            },
        ),
        migrations.CreateModel(
            name='SucursalesEempresas',
            fields=[
                ('numero_sucursal', models.AutoField(db_column='T012NroSucursal', editable=False, primary_key=True, serialize=False)),
                ('sucursal', models.CharField(db_column='T012sucursal', max_length=50)),
                ('direccion', models.CharField(db_column='T012direccion', max_length=50)),
                ('ubicacion_georeferenciada', models.CharField(db_column='T012ubicacionGeoreferenciada', max_length=50)),
                ('direccion_correspondencias', models.CharField(db_column='T012direccionCorrespondencias', max_length=50)),
                ('email_sucursal', models.EmailField(db_column='T012emailSucursal', max_length=255)),
                ('telefono_sucursal', models.CharField(db_column='T012telContactoSucursal', max_length=10)),
                ('es_principal', models.BooleanField(db_column='T012esPrincipal', default=False)),
                ('id_empresa', models.ForeignKey(db_column='T012IdEmpresa', on_delete=django.db.models.deletion.CASCADE, to='seguridad.personas')),
                ('municipio', models.ForeignKey(db_column='T012codMunicipio', on_delete=django.db.models.deletion.CASCADE, to='seguridad.municipio')),
                ('pais_empresa_extranjera', models.ForeignKey(blank=True, db_column='T012cod_PaisEmpresaExtranjera', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.paises')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'T012SucursalesEempresa',
            },
        ),
        migrations.AddField(
            model_name='personas',
            name='sexo',
            field=models.ForeignKey(db_column='T010Cod_Sexo', on_delete=django.db.models.deletion.CASCADE, to='seguridad.sexo'),
        ),
        migrations.AddField(
            model_name='personas',
            name='tipo_documento',
            field=models.ForeignKey(db_column='T010CodTipo_Documento', on_delete=django.db.models.deletion.CASCADE, to='seguridad.tiposdocumento'),
        ),
        migrations.CreateModel(
            name='PermisosModuloRol',
            fields=[
                ('cod_permiso', models.CharField(db_column='TzCodPermiso', max_length=100, primary_key=True, serialize=False)),
                ('id_modulo', models.ForeignKey(blank=True, db_column='TzIdModulo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.permisosmodulo')),
                ('id_rol', models.ForeignKey(blank=True, db_column='TzIdRol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.roles')),
            ],
            options={
                'verbose_name': 'Permiso de modulo de rol',
                'verbose_name_plural': 'Permisos de modulo de roles',
                'db_table': 'TzPermisos_Modulo_Rol',
            },
        ),
        migrations.CreateModel(
            name='HistoricoEmails',
            fields=[
                ('id_histo_email', models.AutoField(db_column='T016IdHistoEmail', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='T016email', max_length=255)),
                ('fecha_cambio', models.DateTimeField(auto_now=True, db_column='T016fechaCambio')),
                ('id_persona', models.ForeignKey(blank=True, db_column='T016Id_Persona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas')),
            ],
            options={
                'verbose_name': 'Historico de email',
                'verbose_name_plural': 'Históricos de email',
                'db_table': 'T016HistoricoEmails',
            },
        ),
        migrations.CreateModel(
            name='HistoricoDireccion',
            fields=[
                ('id_historico_direccion', models.AutoField(db_column='T015IdHistoDireccion', editable=False, primary_key=True, serialize=False)),
                ('direccion', models.CharField(db_column='T015direccion', max_length=255)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_column='T015fechaCambio')),
                ('cod_municipio', models.ForeignKey(blank=True, db_column='T015CodMunicipio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.municipio')),
                ('id_persona', models.ForeignKey(blank=True, db_column='T015Id_Persona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas')),
            ],
            options={
                'verbose_name': 'Histórico de dirección ',
                'verbose_name_plural': 'Histórico de direcciones',
                'db_table': 'T015HistoricoDirecciones',
            },
        ),
        migrations.CreateModel(
            name='HistoricoActivacion',
            fields=[
                ('id_historico', models.AutoField(db_column='T014IdHistorico', editable=False, primary_key=True, serialize=False)),
                ('fecha_operacion', models.DateTimeField(auto_now=True, db_column='T014fechaOperacion')),
                ('justificacion', models.TextField(db_column='T014justificacion')),
                ('cod_operacion', models.ForeignKey(db_column='T014Cod_Operacion', on_delete=django.db.models.deletion.CASCADE, to='seguridad.operacionessobreusuario')),
                ('id_usuario_afectado', models.ForeignKey(db_column='T014Id_Usuario_Afectado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_operador', models.ForeignKey(db_column='T014usuarioOperador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarioOperador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de activación',
                'verbose_name_plural': 'Histórico de activaciones',
                'db_table': 'T014HistoricoActivacion',
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(blank=True, db_column='T002Cod_Pais', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.paises'),
        ),
        migrations.CreateModel(
            name='ClasesTerceroPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.ForeignKey(blank=True, db_column='T011IdTipoTercero', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas')),
                ('id_tipo_tercero', models.ForeignKey(blank=True, db_column='T011IdPersona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.clasestercero')),
            ],
            options={
                'verbose_name': 'Clase tercero persona',
                'verbose_name_plural': 'Clase tercero personas',
                'db_table': 'T011ClasesTercero_Persona',
            },
        ),
        migrations.CreateModel(
            name='Auditorias',
            fields=[
                ('id_auditoria', models.AutoField(db_column='TzIdAuditoria', editable=False, primary_key=True, serialize=False)),
                ('fecha_accion', models.DateField(db_column='TzfechaAccion')),
                ('subsistema', models.CharField(db_column='Tzsubsistema', max_length=50)),
                ('dirip', models.CharField(db_column='Tzdirip', max_length=50)),
                ('descripcion', models.TextField(db_column='Tzdescripcion')),
                ('valores_actualizados', models.CharField(db_column='TzvaloresActualizado', max_length=50)),
                ('id_cod_operacion', models.ForeignKey(blank=True, db_column='TzCod_Operacion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.permisos')),
                ('id_modulo', models.ForeignKey(blank=True, db_column='TzId_Modulo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.modulos')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='TzId_Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'db_table': 'TzAuditorias',
            },
        ),
        migrations.CreateModel(
            name='ApoderadoPersona',
            fields=[
                ('id_proceso', models.CharField(db_column='T013IdProceso', max_length=50)),
                ('consecutivo_del_proceso', models.AutoField(db_column='T013ConsecDelProceso', editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(db_column='T013fechaInicio')),
                ('fecha_cierre', models.DateTimeField(db_column='T013fechaCierre')),
                ('persona_apoderada', models.ForeignKey(db_column='T013IdPersonaApoderada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_apoderada', to='seguridad.personas')),
                ('persona_poderdante', models.ForeignKey(blank=True, db_column='T013IdPersonaPoderdante', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas')),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
                'db_table': 'T013Apoderados_Persona',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='persona',
            field=models.OneToOneField(blank=True, db_column='TzId_Persona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
