# Generated by Django 4.1.1 on 2022-10-21 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoactivacion',
            name='usuario_operador',
            field=models.ForeignKey(blank=True, db_column='T014usuarioOperador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarioOperador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariosrol',
            name='id_rol',
            field=models.ForeignKey(db_column='TzIdRol', on_delete=django.db.models.deletion.CASCADE, to='seguridad.roles'),
        ),
    ]
