# Generated by Django 4.1.1 on 2022-10-10 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='persona',
            field=models.OneToOneField(db_column='TzId_Persona', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas'),
        ),
    ]
