# Generated by Django 4.1.1 on 2022-10-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocivil',
            name='precargado',
            field=models.BooleanField(db_column='T006RegistroPrecargado', default=False),
        ),
        migrations.AddField(
            model_name='roles',
            name='Rol_sistema',
            field=models.BooleanField(db_column='TXrolDelSistema', default=False),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='precargado',
            field=models.BooleanField(db_column='T006RegistroPrecargado', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='creado_por_portal',
            field=models.BooleanField(db_column='TzcreadoPorPortal', default=False),
        ),
        migrations.AlterField(
            model_name='auditorias',
            name='subsistema',
            field=models.CharField(choices=[('ALMA', 'Almacen'), ('CONS', 'Conservación'), ('GEST', 'Gestión Documental'), ('RECU', 'Recurso Hídrico'), ('TRAM', 'Trámites y Servicios'), ('PLAN', 'Seguimiento a Planes'), ('RECA', 'Recaudo'), ('SEGU', 'Seguridad'), ('TRNV', 'Transversal')], db_column='Tzsubsistema', max_length=4),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='subsistema',
            field=models.CharField(choices=[('ALMA', 'Almacen'), ('CONS', 'Conservación'), ('GEST', 'Gestión Documental'), ('RECU', 'Recurso Hídrico'), ('TRAM', 'Trámites y Servicios'), ('PLAN', 'Seguimiento a Planes'), ('RECA', 'Recaudo'), ('SEGU', 'Seguridad'), ('TRNV', 'Transversal')], db_column='Tzsubsistema', max_length=4),
        ),
    ]
