# Generated by Django 4.1.1 on 2022-10-04 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosrol',
            name='id_rol',
            field=models.ForeignKey(db_column='TzIdRol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.roles'),
        ),
    ]
