# Generated by Django 4.1.1 on 2022-10-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='cod_permiso',
            field=models.CharField(choices=[('CR', 'Crear'), ('BO', 'Borrar'), ('CO', 'Consultar'), ('EJ', 'Ejecutar'), ('AP', 'Aprobar')], db_column='TzCodPermiso', max_length=2, primary_key=True, serialize=False),
        ),
    ]
