# Generated by Django 4.1.1 on 2022-10-29 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditorias',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='auditorias',
            name='id_usuari',
            field=models.ForeignKey(blank=True, db_column='TzId_Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
