# Generated by Django 4.1.1 on 2022-10-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacionessobreusuario',
            name='cod_operacion',
            field=models.CharField(db_column='T008CodOperacion', editable=False, max_length=1, primary_key=True, serialize=False),
        ),
    ]
