# Generated by Django 4.1.1 on 2022-10-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='numero_documento',
            field=models.CharField(db_column='T010nroDocumento', max_length=20),
        ),
    ]
