# Generated by Django 4.1.1 on 2022-11-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadocivil',
            name='activo',
            field=models.BooleanField(db_column='T005activo', default=True),
        ),
        migrations.AddField(
            model_name='estadocivil',
            name='item_ya_usado',
            field=models.BooleanField(db_column='T005itemYaUsado', default=False),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='activo',
            field=models.BooleanField(db_column='T006activo', default=True),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='item_ya_usado',
            field=models.BooleanField(db_column='T006itemYaUsado', default=False),
        ),
        migrations.AlterField(
            model_name='estadocivil',
            name='precargado',
            field=models.BooleanField(db_column='T005registroPrecargado', default=False),
        ),
    ]
