# Generated by Django 4.1.1 on 2022-09-29 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_usuario_creador',
            field=models.ForeignKey(db_column='TzId_Usuario_Creador', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
