# Generated by Django 4.1.1 on 2022-10-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='cod_permiso',
            field=models.CharField(choices=[('CR', 'Crear'), ('BO', 'Borrar'), ('CO', 'Consultar'), ('EJ', 'Ejecutar'), ('AP', 'Aprobar')], db_column='TzCodPermiso', max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personas',
            name='tipo_documento',
            field=models.ForeignKey(db_column='T010Cod_TipoDocumento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_documento', to='seguridad.tipodocumento'),
        ),
    ]
