# Generated by Django 4.1.1 on 2022-10-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_remove_auditorias_id_usuario_auditorias_id_usuari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditorias',
            old_name='id_usuari',
            new_name='id_usuario',
        ),
    ]
