# Generated by Django 4.1.1 on 2022-09-29 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_user_id_usuario_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personas',
            name='representate_legal',
        ),
        migrations.AddField(
            model_name='personas',
            name='representante_legal',
            field=models.ForeignKey(blank=True, db_column='T010Id_PersonaRepLegal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='cod_permiso',
            field=models.CharField(db_column='TzCodPermiso', editable=False, max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personas',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('I', 'Intersexual')], db_column='T010Cod_Sexo', max_length=1),
        ),
        migrations.DeleteModel(
            name='Sexo',
        ),
    ]
