# Generated by Django 4.1.1 on 2022-09-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_user_activated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apoderadopersona',
            options={'verbose_name': 'Apoderado', 'verbose_name_plural': 'Apoderados'},
        ),
        migrations.AlterModelOptions(
            name='auditorias',
            options={'verbose_name': 'Auditoría', 'verbose_name_plural': 'Auditorías'},
        ),
        migrations.AlterModelOptions(
            name='clasestercero',
            options={'verbose_name': 'Clase tercero', 'verbose_name_plural': 'Clase terceros'},
        ),
        migrations.AlterModelOptions(
            name='clasesterceropersona',
            options={'verbose_name': 'Clase tercero persona', 'verbose_name_plural': 'Clase tercero personas'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'verbose_name': 'Estado civil', 'verbose_name_plural': 'Estado civil'},
        ),
        migrations.AlterModelOptions(
            name='historicoactivacion',
            options={'verbose_name': 'Histórico de activación', 'verbose_name_plural': 'Histórico de activaciones'},
        ),
        migrations.AlterModelOptions(
            name='historicodireccion',
            options={'verbose_name': 'Histórico de dirección ', 'verbose_name_plural': 'Histórico de direcciones'},
        ),
        migrations.AlterModelOptions(
            name='historicoemails',
            options={'verbose_name': 'Historico de email', 'verbose_name_plural': 'Históricos de email'},
        ),
        migrations.AlterModelOptions(
            name='modulos',
            options={'verbose_name': 'Modulo', 'verbose_name_plural': 'Modulos'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='operacionessobreusuario',
            options={'verbose_name': 'Operacion sobre usuario', 'verbose_name_plural': 'Operaciones sobre usuario'},
        ),
        migrations.AlterModelOptions(
            name='paises',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='permisos',
            options={'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='permisosmodulo',
            options={'verbose_name': 'Permiso de módulo', 'verbose_name_plural': 'Permisos de módulo'},
        ),
        migrations.AlterModelOptions(
            name='permisosmodulorol',
            options={'verbose_name': 'Permiso de modulo de rol', 'verbose_name_plural': 'Permisos de modulo de roles'},
        ),
        migrations.AlterModelOptions(
            name='personas',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='sexo',
            options={'verbose_name': 'Sexo', 'verbose_name_plural': 'Sexo'},
        ),
        migrations.AlterModelOptions(
            name='sucursaleseempresas',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='tiposdocumento',
            options={'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de documento'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuariosrol',
            options={'verbose_name': 'Rol de usuario', 'verbose_name_plural': 'Roles de usuario'},
        ),
    ]
