# Generated by Django 4.1.1 on 2022-10-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_estadocivil_precargado_roles_rol_sistema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocivil',
            name='cod_estado_civil',
            field=models.CharField(db_column='T005Cod_Estado_Civil', max_length=1, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='cod_tipo_documento',
            field=models.CharField(db_column='T006CodTipoDocumento', max_length=2, primary_key=True, serialize=False, unique=True),
        ),
    ]
