# Generated by Django 4.1.1 on 2022-10-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_permisos_cod_permiso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='estado_civil',
            field=models.ForeignKey(blank=True, db_column='T010Cod_EstadoCivil', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estado_civil', to='seguridad.estadocivil'),
        ),
    ]
