# Generated by Django 4.1.1 on 2022-10-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_user_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, db_column='T010FechaNacimiento', null=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='telefono_celular',
            field=models.CharField(blank=True, db_column='T010telCelularPersona', max_length=15, null=True),
        ),
    ]
