# Generated by Django 4.1.1 on 2022-10-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguridad", "0003_alter_estadocivil_cod_estado_civil_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginerroneo",
            name="dirip",
            field=models.GenericIPAddressField(
                blank=True, db_column="TzdirIP", null=True
            ),
        ),
    ]
