# Generated by Django 4.1.1 on 2022-10-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_alter_shortener_long_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortener',
            options={'ordering': ['-created'], 'verbose_name': 'Acortador', 'verbose_name_plural': 'Acortadores'},
        ),
        migrations.AlterModelTable(
            name='shortener',
            table='Shortener',
        ),
    ]
