# Generated by Django 4.1.1 on 2022-11-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_rename_id_usuari_auditorias_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nombre_de_usuario',
            field=models.CharField(db_column='TznombreUsuario', max_length=30, unique=True),
        ),
    ]
