# Generated by Django 4.1.1 on 2022-10-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguridad", "0004_alter_loginerroneo_dirip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="dirip",
            field=models.GenericIPAddressField(
                blank=True, db_column="TzdirIP", null=True
            ),
        ),
    ]
