# Generated by Django 4.1.1 on 2022-10-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguridad", "0005_alter_login_dirip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="dirip",
            field=models.CharField(db_column="TzdirIP", max_length=40),
        ),
        migrations.AlterField(
            model_name="loginerroneo",
            name="dirip",
            field=models.CharField(db_column="TzdirIP", max_length=40),
        ),
    ]
