# Generated by Django 4.1.1 on 2022-10-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguridad", "0008_alter_login_dispositivo_conexion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="dispositivo_conexion",
            field=models.CharField(db_column="TzdispositivoConexion", max_length=30),
        ),
        migrations.AlterField(
            model_name="loginerroneo",
            name="dispositivo_conexion",
            field=models.CharField(db_column="TzdispositivoConexion", max_length=30),
        ),
    ]
