# Generated by Django 4.1.1 on 2022-10-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguridad", "0009_alter_login_dispositivo_conexion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginerroneo",
            name="fecha_login_error",
            field=models.DateTimeField(auto_now=True, db_column="TzfechaLoginError"),
        ),
    ]
