# Generated by Django 4.1.1 on 2022-10-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguridad", "0010_alter_loginerroneo_fecha_login_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="login",
            name="fecha_hora_cierre_sesion",
            field=models.DateTimeField(
                auto_now=True, db_column="TzfechaHoraCierreSesion", null=True
            ),
        ),
        migrations.AlterField(
            model_name="login",
            name="fecha_login",
            field=models.DateTimeField(auto_now_add=True, db_column="TzfechaLogin"),
        ),
    ]
