# Generated by Django 4.1.1 on 2022-11-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('gestion_documental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionSeriesSubDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_clas_serie_doc', models.IntegerField(db_column='T214CodClasSerieDoc')),
                ('tipo_clasificacion', models.CharField(choices=[('P', 'Público'), ('C', 'Controlado'), ('R', 'Rerservado')], db_column='T214tipoClasificacion', max_length=20)),
            ],
            options={
                'verbose_name': 'Clasificacion serie sub Doc ',
                'verbose_name_plural': 'Clasificaciones serie sub Doc',
                'db_table': 'T214ClasificacionSeriesSubDoc',
            },
        ),
        migrations.CreateModel(
            name='PermisosGD',
            fields=[
                ('permisos_GD', models.AutoField(db_column='T213IdPermisosGD', editable=False, primary_key=True, serialize=False)),
                ('tipo_permiso', models.CharField(db_column='T213tipoPermiso', max_length=20)),
            ],
            options={
                'verbose_name': 'Permiso GD',
                'verbose_name_plural': 'Permisos GD',
                'db_table': 'T213PermisosGD',
            },
        ),
        migrations.CreateModel(
            name='TablasControAcceso',
            fields=[
                ('id_TCA', models.AutoField(db_column='T216IdTCA', editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(db_column='T216version', max_length=30, unique=True)),
                ('nombre', models.CharField(db_column='T216nombre', max_length=200, unique=True)),
                ('fecha_terminado', models.DateTimeField(blank=True, db_column='T216fechaTerminado', null=True)),
                ('fecha_puesta_produccion', models.DateTimeField(blank=True, db_column='T216fechaPuestaEnProduccion', null=True)),
                ('fecha_retiro_produccion', models.DateTimeField(blank=True, db_column='T216fechaRetiroDeProduccion', null=True)),
                ('justificacion_nueva_version', models.CharField(blank=True, db_column='T216justificacionNuevaVersion', max_length=500, null=True)),
                ('ruta_soporte', models.CharField(blank=True, db_column='T216rutaSoporte', max_length=200, null=True)),
                ('actual', models.BooleanField(db_column='T216actual', default=False)),
                ('id_CCD', models.ForeignKey(db_column='T216Id_CCD', on_delete=django.db.models.deletion.CASCADE, to='almacen.cuadrosclasificaciondocumental')),
            ],
            options={
                'verbose_name': 'Tabla de control de acceso',
                'verbose_name_plural': 'Tablas de control de acceso',
                'db_table': 'T216TablasControlAcceso',
            },
        ),
        migrations.CreateModel(
            name='CCD_Clasif_Cargos_UndCargo_Permisos',
            fields=[
                ('id_serie_sub_serie_cargo_permiso_GD', models.AutoField(db_column='T215IdSerieSubserieCargoPermisoGD', editable=False, primary_key=True, serialize=False)),
                ('id_cargo_persona', models.CharField(db_column='T215Id_CargoPersona', max_length=10)),
                ('id_unidad_org_cargo', models.CharField(db_column='T215Id_UnidadOrgCargo', max_length=10)),
                ('cod_class_serie_Doc', models.ForeignKey(db_column='T215Cod_ClasSerieDoc', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.clasificacionseriessubdoc')),
                ('id_TCA', models.ForeignKey(db_column='T215Id_TCA', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.tablascontroacceso')),
                ('id_permiso_GD', models.ForeignKey(db_column='T215Id_PermisoGD', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.permisosgd')),
                ('id_serie_sub_serie_Doc', models.ForeignKey(db_column='T215Id_SerieSubserieDoc', on_delete=django.db.models.deletion.CASCADE, to='almacen.seriessubseriesunidadorg')),
            ],
            options={
                'verbose_name': 'clasificación cargo unidad cargo y permisos',
                'verbose_name_plural': 'clasificaciones cargos unidad cargo y permisos',
                'db_table': 'T215CCD_Clasif_Cargos_UndCargo_Permisos',
            },
        ),
    ]
