# Generated by Django 4.1.1 on 2022-11-22 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        ('gestion_documental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatosTiposMedio',
            fields=[
                ('id_formato_tipo_medio', models.AutoField(db_column='T210IdFormato_TipoMedio', editable=False, primary_key=True, serialize=False)),
                ('cod_tipo_medio_doc', models.CharField(choices=[('E', 'Electrónico'), ('F', 'Físico'), ('H', 'Híbrido')], db_column='T210Cod_TipoMedioDoc', max_length=1)),
                ('nombre', models.CharField(db_column='T210nombre', max_length=20, unique=True)),
                ('registro_precargado', models.BooleanField(db_column='T210regsitroPrecargado', default=False)),
                ('activo', models.BooleanField(db_column='T210activo', default=True)),
                ('item_ya_usado', models.BooleanField(db_column='T210itemYaUsado', default=False)),
            ],
            options={
                'verbose_name': 'Formato Tipo Medio',
                'verbose_name_plural': 'Formatos Tipos Medios',
                'db_table': 'T210Formatos_TiposMedio',
            },
        ),
        migrations.CreateModel(
            name='FormatosTiposMedioTipoDoc',
            fields=[
                ('id_formato_tipomedio_tipo_doc', models.AutoField(db_column='T217IdFormato_TipoMedio_TipoDoc_TRD', editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Formatos Tipos Medio Tipologia Documental TRD',
                'verbose_name_plural': 'Formatos Tipos Medio Tipologia Documental TRD',
                'db_table': 'T217Formatos_TiposMedio_TipoDoc_TRD',
            },
        ),
        migrations.CreateModel(
            name='HistoricosSerieSubSeriesUnidadOrgTRD',
            fields=[
                ('historico_serie_subs_unidadorg_trd', models.AutoField(db_column='T219Historico_Serie_SubS_UnidadOrg_TRD', editable=False, primary_key=True, serialize=False)),
                ('cod_disposicion_final', models.CharField(db_column='T219CodDisposicionFinal', max_length=1)),
                ('digitalizacion_disp_final', models.BooleanField(db_column='T219digitalizacionDispFinal', default=False)),
                ('tiempo_retencion_ag', models.PositiveSmallIntegerField(db_column='T219tiempoRetencionAG')),
                ('tiempo_retencion_ac', models.PositiveSmallIntegerField(db_column='T219tiempoRetencionAC')),
                ('descripcion_procedimiento', models.TextField(db_column='T219descripcionProcedimiento', max_length=500)),
                ('fecha_registro_historico', models.DateTimeField(auto_now=True, db_column='T219FechaRegistroDelHisto')),
                ('justificacion', models.CharField(blank=True, db_column='T219justificacion', max_length=255, null=True)),
                ('ruta_archivo', models.CharField(blank=True, db_column='T219rutaArchivo', max_length=255, null=True)),
                ('id_persona_cambia', models.ForeignKey(blank=True, db_column='T219Id_PersonaCambia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas')),
            ],
            options={
                'verbose_name': 'Historicos Serie SubSeries UnidadOrg TRD',
                'verbose_name_plural': 'Historicos Serie SubSeries UnidadOrg TRD',
                'db_table': 'T219Historicos_Serie_SubS_UnidadOrg_TRD',
            },
        ),
        migrations.CreateModel(
            name='SeriesSubSUnidadOrgTRD',
            fields=[
                ('id_serie_subs_unidadorg_trd', models.AutoField(db_column='T218IdSerie_SubS_UnidadOrg_TRD', editable=False, primary_key=True, serialize=False)),
                ('cod_disposicion_final', models.CharField(choices=[('CT', 'Conservación Total'), ('E', 'Eliminación'), ('S', 'Selección')], db_column='T218Cod_DisposicionFinal', max_length=20)),
                ('digitalizacion_dis_final', models.BooleanField(db_column='T218digitalizacionDispFinal', default=False)),
                ('tiempo_retencion_ag', models.PositiveSmallIntegerField(db_column='T218tiempoRetencionAG')),
                ('tiempo_retencion_ac', models.PositiveSmallIntegerField(db_column='T218tiempoRetencionAC')),
                ('descripcion_procedimiento', models.TextField(db_column='T218descripcionProcedimiento', max_length=500)),
                ('fecha_registro', models.DateTimeField(auto_now=True, db_column='T218fechaRegistro')),
                ('justificacion_cambio', models.CharField(blank=True, db_column='T218JustificacionCambio', max_length=255, null=True)),
                ('ruta_archivo_cambio', models.FileField(blank=True, db_column='T218RutaArchivoCambio', null=True, upload_to='')),
                ('id_persona_cambia', models.ForeignKey(blank=True, db_column='T218Id_PersonaCambia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas')),
            ],
            options={
                'verbose_name': 'Series Subseries Unidades Organizacionales TRD',
                'db_table': 'T218Series_SubS_UnidadOrg_TRD',
            },
        ),
        migrations.CreateModel(
            name='SeriesSubSUnidadOrgTRDTipologias',
            fields=[
                ('id_serie_subserie_tipologia', models.AutoField(db_column='T211IdSerieSubserieTipologia', editable=False, primary_key=True, serialize=False)),
                ('id_serie_subserie_unidadorg_trd', models.ForeignKey(db_column='T211IdSerie_SubS_UnidadOrg_TRD', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.seriessubsunidadorgtrd')),
            ],
            options={
                'verbose_name': 'Series SubSeries Unidad Organizacional TRD Tipologias',
                'verbose_name_plural': 'Series SubSeries Unidad Organizacional TRD Tipologias',
                'db_table': 'T211Series_SubS_UnidadOrg_TRD_Tipologias',
            },
        ),
        migrations.CreateModel(
            name='TiposMediosDocumentos',
            fields=[
                ('cod_tipo_medio_doc', models.CharField(db_column='T209Cod_TipoSoporteDoc', editable=False, max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T209nombre', max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo Soporte Documento',
                'verbose_name_plural': 'Tipos Soportes Documentos',
                'db_table': 'T209TiposSoporteDocumentos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='seriessubseriesunidadestipologias',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='seriessubseriesunidadestipologias',
            name='id_serie_subserie_doc',
        ),
        migrations.RemoveField(
            model_name='seriessubseriesunidadestipologias',
            name='id_tipologia_documental',
        ),
        migrations.RemoveField(
            model_name='tipologiasdocumentales',
            name='cod_tipo_soporte_doc',
        ),
        migrations.AddField(
            model_name='tablaretenciondocumental',
            name='cambios_por_confirmar',
            field=models.BooleanField(db_column='T212cambiosPorConfirmar', default=False),
        ),
        migrations.AddField(
            model_name='tipologiasdocumentales',
            name='activo',
            field=models.BooleanField(db_column='T208activo', default=True),
        ),
        migrations.AddField(
            model_name='tipologiasdocumentales',
            name='cod_tipo_medio_doc',
            field=models.CharField(choices=[('E', 'Electrónico'), ('F', 'Físico'), ('H', 'Híbrido')], db_column='T208Cod_TipoMedioDoc', default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipologiasdocumentales',
            name='fecha_desactivacion',
            field=models.DateTimeField(blank=True, db_column='T208FechaDesactivacion', null=True),
        ),
        migrations.AddField(
            model_name='tipologiasdocumentales',
            name='id_persona_desactiva',
            field=models.ForeignKey(blank=True, db_column='T208Id_PersonaQueDesactiva', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas'),
        ),
        migrations.AddField(
            model_name='tipologiasdocumentales',
            name='justificacion_desactivacion',
            field=models.CharField(blank=True, db_column='T208justificacionDesactivacion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cuadrosclasificaciondocumental',
            name='fecha_puesta_produccion',
            field=models.DateTimeField(blank=True, db_column='T206fechaPuestaEnProduccion', null=True),
        ),
        migrations.AlterField(
            model_name='cuadrosclasificaciondocumental',
            name='fecha_retiro_produccion',
            field=models.DateTimeField(blank=True, db_column='T206fechaRetiroDeProduccion', null=True),
        ),
        migrations.AlterField(
            model_name='cuadrosclasificaciondocumental',
            name='nombre',
            field=models.CharField(db_column='T206nombre', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cuadrosclasificaciondocumental',
            name='version',
            field=models.CharField(db_column='T206version', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='disposicionfinalseries',
            name='cod_disposicion_final',
            field=models.CharField(db_column='T207CodDisposicionFinal', editable=False, max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seriesdoc',
            name='id_serie_doc',
            field=models.AutoField(db_column='T203IdSerieDocCCD', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seriessubseriesunidadorg',
            name='id_serie_doc',
            field=models.ForeignKey(db_column='T205Id_SerieDocCCD', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.seriesdoc'),
        ),
        migrations.AlterField(
            model_name='seriessubseriesunidadorg',
            name='id_serie_subserie_doc',
            field=models.AutoField(db_column='T205IdSerieSubserieDoc', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seriessubseriesunidadorg',
            name='id_sub_serie_doc',
            field=models.ForeignKey(blank=True, db_column='T205Id_SubserieDocCCD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_documental.subseriesdoc'),
        ),
        migrations.AlterField(
            model_name='subseriesdoc',
            name='id_subserie_doc',
            field=models.AutoField(db_column='T204IdSubserieDocCCD', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipologiasdocumentales',
            name='id_tipologia_documental',
            field=models.AutoField(db_column='T208IdTipologiaDoc_TRD', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='seriessubseriesunidadorg',
            table='T205Series_Subseries_UnidadOrg_CCD',
        ),
        migrations.DeleteModel(
            name='FormatosTipoSoporte',
        ),
        migrations.DeleteModel(
            name='SeriesSubSeriesUnidadesTipologias',
        ),
        migrations.DeleteModel(
            name='TiposSoportesDocumentos',
        ),
        migrations.AddField(
            model_name='seriessubsunidadorgtrdtipologias',
            name='id_tipologia_doc',
            field=models.ForeignKey(db_column='T211IdTipologiaDoc_TRD', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.tipologiasdocumentales'),
        ),
        migrations.AddField(
            model_name='seriessubsunidadorgtrd',
            name='id_serie_subserie_doc',
            field=models.ForeignKey(db_column='T218Id_SerieSubserieDoc', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.seriessubseriesunidadorg'),
        ),
        migrations.AddField(
            model_name='seriessubsunidadorgtrd',
            name='id_trd',
            field=models.ForeignKey(db_column='T2018Id_TRD', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.tablaretenciondocumental'),
        ),
        migrations.AddField(
            model_name='historicosseriesubseriesunidadorgtrd',
            name='id_serie_subs_unidadorg_trd',
            field=models.ForeignKey(db_column='T219IdSerie_SubS_UnidadOrg_TRD', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.seriessubsunidadorgtrd'),
        ),
        migrations.AddField(
            model_name='formatostiposmediotipodoc',
            name='id_formato_tipo_medio',
            field=models.ForeignKey(db_column='T217Id_Formato_TipoMedio', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.tiposmediosdocumentos'),
        ),
        migrations.AddField(
            model_name='formatostiposmediotipodoc',
            name='id_tipologia_doc',
            field=models.ForeignKey(db_column='T217Id_TipologiaDoc', on_delete=django.db.models.deletion.CASCADE, to='gestion_documental.tipologiasdocumentales'),
        ),
        migrations.AlterUniqueTogether(
            name='seriessubsunidadorgtrdtipologias',
            unique_together={('id_serie_subserie_unidadorg_trd', 'id_tipologia_doc')},
        ),
    ]
