# Generated by Django 4.1.1 on 2022-11-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriessubsunidadorgtrd',
            name='cod_disposicion_final',
            field=models.CharField(blank=True, choices=[('CT', 'Conservación Total'), ('E', 'Eliminación'), ('S', 'Selección')], db_column='T218Cod_DisposicionFinal', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seriessubsunidadorgtrd',
            name='descripcion_procedimiento',
            field=models.TextField(blank=True, db_column='T218descripcionProcedimiento', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='seriessubsunidadorgtrd',
            name='tiempo_retencion_ac',
            field=models.PositiveSmallIntegerField(blank=True, db_column='T218tiempoRetencionAC', null=True),
        ),
        migrations.AlterField(
            model_name='seriessubsunidadorgtrd',
            name='tiempo_retencion_ag',
            field=models.PositiveSmallIntegerField(blank=True, db_column='T218tiempoRetencionAG', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='seriessubsunidadorgtrd',
            unique_together={('id_trd', 'id_serie_subserie_doc')},
        ),
    ]
