# Generated by Django 4.1.1 on 2022-11-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatostiposoporte',
            name='nombre',
            field=models.CharField(db_column='T210nombre', max_length=30, unique=True),
        ),
    ]
