# Generated by Django 4.1.1 on 2022-11-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatostiposmedio',
            name='registro_precargado',
            field=models.BooleanField(db_column='T210registroPrecargado', default=False),
        ),
    ]
