# Generated by Django 4.1.1 on 2022-11-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0002_alter_formatostiposoporte_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatostiposoporte',
            name='nombre',
            field=models.CharField(db_column='T210nombre', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tipossoportesdocumentos',
            name='id_tipo_soporte_doc',
            field=models.CharField(db_column='T209Cod_TipoSoporteDoc', editable=False, max_length=2, primary_key=True, serialize=False),
        ),
    ]
