# Generated by Django 4.1.1 on 2022-11-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0002_alter_seriessubsunidadorgtrd_cod_disposicion_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriessubsunidadorgtrd',
            name='digitalizacion_dis_final',
            field=models.BooleanField(blank=True, db_column='T218digitalizacionDispFinal', null=True),
        ),
    ]
