# Generated by Django 4.1.1 on 2022-11-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0003_alter_formatostiposmedio_registro_precargado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposmediosdocumentos',
            options={'verbose_name': 'Tipo Medio Documento', 'verbose_name_plural': 'Tipos Medios Documentos'},
        ),
        migrations.AlterField(
            model_name='formatostiposmedio',
            name='nombre',
            field=models.CharField(db_column='T210nombre', max_length=30),
        ),
        migrations.AlterField(
            model_name='tiposmediosdocumentos',
            name='cod_tipo_medio_doc',
            field=models.CharField(db_column='T209CodTipoMedioDoc', editable=False, max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='tiposmediosdocumentos',
            table='T209TiposMediosDocumentos',
        ),
    ]
