# Generated by Django 4.1.1 on 2022-11-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0003_alter_formatostiposoporte_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipossoportesdocumentos',
            name='id_tipo_soporte_doc',
            field=models.CharField(db_column='T209Cod_TipoSoporteDoc', editable=False, max_length=1, primary_key=True, serialize=False),
        ),
    ]
