# Generated by Django 4.1.1 on 2022-11-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0004_alter_tipossoportesdocumentos_id_tipo_soporte_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipossoportesdocumentos',
            name='nombre',
            field=models.CharField(choices=[('E', 'Electrónico'), ('F', 'Físico'), ('H', 'Híbrido')], db_column='T209nombre', max_length=11),
        ),
    ]
