# Generated by Django 4.1.1 on 2022-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0004_alter_tiposmediosdocumentos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatostiposmedio',
            name='cod_tipo_medio_doc',
            field=models.CharField(choices=[('E', 'Electrónico'), ('F', 'Físico')], db_column='T210Cod_TipoMedioDoc', max_length=1),
        ),
    ]
