# Generated by Django 4.1.1 on 2022-11-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0005_alter_formatostiposmedio_cod_tipo_medio_doc'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formatostiposmedio',
            unique_together={('cod_tipo_medio_doc', 'nombre')},
        ),
    ]
