# Generated by Django 4.1.1 on 2022-11-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0006_alter_formatostiposoporte_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipologiasdocumentales',
            name='cod_tipo_soporte_doc',
            field=models.CharField(choices=[('E', 'Electrónico'), ('F', 'Físico'), ('H', 'Híbrido')], db_column='T208Cod_TipoSoporteDoc', max_length=1),
        ),
        migrations.AlterField(
            model_name='tipossoportesdocumentos',
            name='nombre',
            field=models.CharField(db_column='T209nombre', max_length=11),
        ),
    ]
