# Generated by Django 4.1.1 on 2022-11-17 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documental', '0007_alter_tipologiasdocumentales_cod_tipo_soporte_doc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipologiasdocumentales',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipologia Documental', 'verbose_name_plural': 'Tipologias Documentales'},
        ),
    ]
