# Generated by Django 4.1.1 on 2022-10-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosArticulos',
            fields=[
                ('cod_estado', models.AutoField(db_column='T051CodEstado', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T051nombre', max_length=30)),
            ],
            options={
                'verbose_name': 'Estado artículo',
                'verbose_name_plural': 'Estados artículos',
                'db_table': 'T051EstadosArticulo',
            },
        ),
        migrations.CreateModel(
            name='Magnitudes',
            fields=[
                ('cod_magnitud', models.AutoField(db_column='T054CodMagnitud', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T054nombre', max_length=30)),
            ],
            options={
                'verbose_name': 'Magnitud',
                'verbose_name_plural': 'Magnitudes',
                'db_table': 'T054Magnitudes',
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(db_column='T052IdMarca', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T052nombre', max_length=30)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'T052Marcas',
            },
        ),
        migrations.CreateModel(
            name='PorcentajesIVA',
            fields=[
                ('id_porcentaje_iva', models.AutoField(db_column='T053IdPorcentajeIVA', editable=False, primary_key=True, serialize=False)),
                ('porcentaje', models.FloatField(db_column='T053porcentaje')),
                ('observacion', models.CharField(db_column='T053observacion', max_length=100)),
            ],
            options={
                'verbose_name': 'Porcentaje IVA',
                'verbose_name_plural': 'Porcentajes IVA',
                'db_table': 'T053PorcentajesIVA',
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id_unidad_medida', models.AutoField(db_column='T055IdUnidadMedida', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T055nombre', max_length=30)),
                ('abreviatura', models.CharField(db_column='T055abreviatura', max_length=5)),
                ('cod_magnitud', models.ForeignKey(db_column='T055Cod_Magnitud', on_delete=django.db.models.deletion.CASCADE, to='almacen.magnitudes')),
            ],
            options={
                'verbose_name': 'Unidad medida',
                'verbose_name_plural': 'Unidades medida',
                'db_table': 'T055UnidadesMedida',
            },
        ),
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id_bodega', models.AutoField(db_column='T056IdBodega', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T056nombre', max_length=30)),
                ('direccion', models.CharField(blank=True, db_column='T056direccion', max_length=255, null=True)),
                ('id_responsable', models.IntegerField(db_column='T056Id_Responsable')),
                ('es_principal', models.CharField(db_column='T056esPrincipal', max_length=30)),
                ('cod_municipio', models.ForeignKey(db_column='T056Cod_Municipio', on_delete=django.db.models.deletion.CASCADE, to='seguridad.municipio')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'db_table': 'T056Bodegas',
            },
        ),
    ]
