<<<<<<< Updated upstream
# Generated by Django 4.1.1 on 2022-11-11 19:29
=======
# Generated by Django 4.1.1 on 2022-11-11 20:05
>>>>>>> Stashed changes

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargo', models.AutoField(db_column='T009IdCargo', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T009nombre', max_length=50, unique=True)),
                ('activo', models.BooleanField(db_column='T009activo', default=False)),
                ('item_usado', models.BooleanField(db_column='T009itemYaUsado', default=False)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'T009Cargos',
            },
        ),
        migrations.CreateModel(
            name='CuadrosClasificacionDocumental',
            fields=[
                ('id_ccd', models.AutoField(db_column='T206IdCCD', editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(db_column='T206version', max_length=30, unique=True)),
                ('nombre', models.CharField(db_column='T206nombre', max_length=200, unique=True)),
                ('fecha_terminado', models.DateTimeField(blank=True, db_column='T206fechaTerminado', null=True)),
                ('fecha_puesta_produccion', models.DateTimeField(blank=True, db_column='T206fechaPuestaProduccion', null=True)),
                ('fecha_retiro_produccion', models.DateTimeField(blank=True, db_column='T206fechaRetiroProduccion', null=True)),
                ('justificacion', models.CharField(blank=True, db_column='T206justificacionNuevaVersion', max_length=255, null=True)),
                ('ruta_soporte', models.CharField(blank=True, db_column='T206rutaSoporte', max_length=200, null=True)),
                ('actual', models.BooleanField(db_column='T206actual', default=False)),
            ],
            options={
                'verbose_name': 'Cuadro Clasificacion Documental',
                'verbose_name_plural': 'Cuadros Clasificacion Documental',
                'db_table': 'T206CuadrosClasificacionDoc',
            },
        ),
        migrations.CreateModel(
            name='EstadosArticulo',
            fields=[
                ('cod_estado', models.CharField(db_column='T051CodEstado', max_length=1, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(db_column='T051nombre', max_length=20)),
            ],
            options={
                'verbose_name': 'Estado artículo',
                'verbose_name_plural': 'Estados artículos',
                'db_table': 'T051EstadosArticulo',
            },
        ),
        migrations.CreateModel(
            name='Magnitudes',
            fields=[
                ('cod_magnitud', models.AutoField(db_column='T054CodMagnitud', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T054nombre', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Magnitud',
                'verbose_name_plural': 'Magnitudes',
                'db_table': 'T054Magnitudes',
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(db_column='T052IdMarca', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T052nombre', max_length=50, unique=True)),
                ('activo', models.BooleanField(db_column='T052activo', default=True)),
                ('item_ya_usado', models.BooleanField(db_column='T052itemYaUsado', default=False)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'T052Marcas',
            },
        ),
        migrations.CreateModel(
            name='NivelesOrganigrama',
            fields=[
                ('id_nivel_organigrama', models.AutoField(db_column='T018IdNivelOrganigrama', editable=False, primary_key=True, serialize=False)),
                ('orden_nivel', models.SmallIntegerField(db_column='T018ordenDelNivel')),
                ('nombre', models.CharField(db_column='T018nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Nivel Organigrama',
                'verbose_name_plural': 'Niveles Organigrama',
                'db_table': 'T018NivelesOrganigrama',
            },
        ),
        migrations.CreateModel(
            name='Organigramas',
            fields=[
                ('id_organigrama', models.AutoField(db_column='T017IdOrganigrama', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T017nombre', max_length=50, unique=True)),
                ('fecha_terminado', models.DateTimeField(blank=True, db_column='T017fechaTerminado', null=True)),
                ('descripcion', models.CharField(db_column='T017descripcion', max_length=255)),
                ('fecha_puesta_produccion', models.DateTimeField(blank=True, db_column='T017fechaPuestaEnProduccion', null=True)),
                ('fecha_retiro_produccion', models.DateField(blank=True, db_column='T017fechaRetiroDeProduccion', null=True)),
                ('justificacion_nueva_version', models.DateTimeField(blank=True, db_column='T017justificacionNuevaVersion', max_length=255, null=True)),
                ('version', models.CharField(db_column='T017version', max_length=10)),
                ('actual', models.BooleanField(db_column='T017actual', default=False)),
                ('ruta_resolucion', models.CharField(blank=True, db_column='T017rutaResolucion', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Organigrama',
                'verbose_name_plural': 'Organigramas',
                'db_table': 'T017Organigramas',
            },
        ),
        migrations.CreateModel(
            name='PorcentajesIVA',
            fields=[
                ('id_porcentaje_iva', models.AutoField(db_column='T053IdPorcentajeIVA', editable=False, primary_key=True, serialize=False)),
                ('porcentaje', models.FloatField(db_column='T053porcentaje', unique=True)),
                ('observacion', models.CharField(db_column='T053observacion', max_length=255)),
                ('registro_precargado', models.BooleanField(db_column='T053registroPrecargado', default=False)),
                ('activo', models.BooleanField(db_column='T053activo', default=True)),
                ('item_ya_usado', models.BooleanField(db_column='T053itemYaUsado', default=False)),
            ],
            options={
                'verbose_name': 'Porcentaje IVA',
                'verbose_name_plural': 'Porcentajes IVA',
                'db_table': 'T053PorcentajesIVA',
            },
        ),
        migrations.CreateModel(
            name='SeriesDoc',
            fields=[
                ('id_serie_doc', models.AutoField(db_column='T203IdSerieDoc', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T203nombre', max_length=200)),
                ('codigo', models.PositiveBigIntegerField(db_column='T203codigo')),
                ('id_ccd', models.ForeignKey(db_column='T203Id_CCD', on_delete=django.db.models.deletion.CASCADE, to='almacen.cuadrosclasificaciondocumental')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'db_table': 'T203SeriesDoc_CCD',
            },
        ),
        migrations.CreateModel(
            name='UnidadesOrganizacionales',
            fields=[
                ('id_unidad_organizacional', models.AutoField(db_column='T019IdUnidadOrganizacional', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T019nombre', max_length=50)),
                ('codigo', models.CharField(db_column='T019codigo', max_length=10)),
                ('cod_tipo_unidad', models.CharField(choices=[('LI', 'Linea'), ('AP', 'Apoyo'), ('AS', 'Asesor')], db_column='T019codTipoUnidad', max_length=2)),
                ('cod_agrupacion_documental', models.CharField(blank=True, choices=[('SEC', 'Sección'), ('SUB', 'Subsección')], db_column='T019codAgrupacionDocumental', max_length=3, null=True)),
                ('unidad_raiz', models.BooleanField(db_column='T019unidadRaiz', default=False)),
                ('id_nivel_organigrama', models.ForeignKey(db_column='T019Id_NivelOrganigrama', on_delete=django.db.models.deletion.CASCADE, to='almacen.nivelesorganigrama')),
                ('id_organigrama', models.ForeignKey(db_column='T019Id_Organigrama', on_delete=django.db.models.deletion.CASCADE, to='almacen.organigramas')),
                ('id_unidad_org_padre', models.ForeignKey(blank=True, db_column='T019Id_UnidadOrgPadre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.unidadesorganizacionales')),
            ],
            options={
                'verbose_name': 'Unidad organizacional',
                'verbose_name_plural': 'Unidad organizacionales',
                'db_table': 'T019UnidadesOrganizacionales',
                'unique_together': {('id_organigrama', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='UnidadesMedida',
            fields=[
                ('id_unidad_medida', models.AutoField(db_column='T055IdUnidadMedida', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T055nombre', max_length=50, unique=True)),
                ('abreviatura', models.CharField(db_column='T055abreviatura', max_length=5, unique=True)),
                ('precargado', models.BooleanField(db_column='T055registroPrecargado', default=False)),
                ('activo', models.BooleanField(db_column='T055activo', default=True)),
                ('item_ya_usado', models.BooleanField(db_column='T055itemYaUsado', default=False)),
                ('id_magnitud', models.ForeignKey(db_column='T055Id_Magnitud', default=1, on_delete=django.db.models.deletion.CASCADE, to='almacen.magnitudes')),
            ],
            options={
                'verbose_name': 'Unidad medida',
                'verbose_name_plural': 'Unidades medida',
                'db_table': 'T055UnidadesMedida',
            },
        ),
        migrations.CreateModel(
            name='SubseriesDoc',
            fields=[
                ('id_subserie_doc', models.AutoField(db_column='T204IdSubserieDoc', editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T204nombre', max_length=200)),
                ('codigo', models.PositiveBigIntegerField(db_column='T204codigo')),
                ('id_ccd', models.ForeignKey(db_column='T204Id_CCD', on_delete=django.db.models.deletion.CASCADE, to='almacen.cuadrosclasificaciondocumental')),
            ],
            options={
                'verbose_name': 'Subserie',
                'verbose_name_plural': 'Subseries',
                'db_table': 'T204SubseriesDoc_CDD',
                'unique_together': {('id_ccd', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='SeriesSubseriesUnidadOrg',
            fields=[
                ('id_serie_subserie_doc', models.AutoField(db_column='T205SerieSubserieDoc', editable=False, primary_key=True, serialize=False)),
                ('id_serie_doc', models.ForeignKey(db_column='T205Id_SerieDoc', on_delete=django.db.models.deletion.CASCADE, to='almacen.seriesdoc')),
                ('id_sub_serie_doc', models.ForeignKey(blank=True, db_column='T205Id_SubserieDoc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.subseriesdoc')),
                ('id_unidad_organizacional', models.ForeignKey(db_column='T205Id_UnidadOrganizacional', on_delete=django.db.models.deletion.CASCADE, to='almacen.unidadesorganizacionales')),
            ],
            options={
                'verbose_name': 'Serie Subserie Unidad',
                'verbose_name_plural': 'Series Subseries Unidades',
                'db_table': 'T205Series_Subseries_UnidadOrg',
            },
        ),
        migrations.AddField(
            model_name='nivelesorganigrama',
            name='id_organigrama',
            field=models.ForeignKey(db_column='T018Id_Organigrama', on_delete=django.db.models.deletion.CASCADE, to='almacen.organigramas'),
        ),
        migrations.AddField(
            model_name='cuadrosclasificaciondocumental',
            name='id_organigrama',
            field=models.ForeignKey(db_column='T206Id_Organigrama', on_delete=django.db.models.deletion.CASCADE, to='almacen.organigramas'),
        ),
    ]
