# Generated by Django 4.1.1 on 2022-10-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodegas',
            name='id_responsable',
            field=models.ForeignKey(db_column='T056Id_Responsable', on_delete=django.db.models.deletion.CASCADE, to='seguridad.personas'),
        ),
    ]
