# Generated by Django 4.1.1 on 2022-11-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelesorganigrama',
            options={'verbose_name': 'Nivel Organigrama', 'verbose_name_plural': 'Niveles Organigrama'},
        ),
        migrations.AlterModelTable(
            name='nivelesorganigrama',
            table='T018NivelesOrganigrama',
        ),
    ]
