# Generated by Django 4.1.1 on 2022-11-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadesmedida',
            name='id_magnitud',
            field=models.CharField(choices=[('1', 'Longitud'), ('2', 'Volumen'), ('3', 'Cantidad'), ('4', 'Peso'), ('5', 'Superficie'), ('6', 'Temperatura'), ('7', 'Tiempo')], db_column='T055Id_Magnitud', max_length=1),
        ),
    ]
