# Generated by Django 4.1.1 on 2022-11-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organigramas',
            name='ruta_resolucion',
            field=models.FileField(blank=True, db_column='T017rutaResolucion', null=True, upload_to=''),
        ),
    ]
