# Generated by Django 4.1.1 on 2022-11-21 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
        ('almacen', '0002_alter_unidadesmedida_id_magnitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MetodosValoracionArticulos',
            fields=[
                ('cod_metodo_valoracion', models.AutoField(db_column='T058CodMetodoValoracion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T058nombre', max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, db_column='T058descripccion', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Metodo valoracion articulo',
                'verbose_name_plural': 'Metodos valoracion articulo',
                'db_table': 'T058MetodosValoracionArticulos',
            },
        ),
        migrations.CreateModel(
            name='ProgramacionMantenimientos',
            fields=[
                ('id_programacion_mtto', models.AutoField(db_column='T069IdProgramacionMtto', primary_key=True, serialize=False)),
                ('cod_tipo_mantenimiento', models.CharField(db_column='T069codTipoMantenimiento', max_length=1)),
                ('fecha_generada', models.DateField(db_column='T069fechaGenerada')),
                ('fecha_programada', models.DateField(db_column='T069fechaProgramada')),
                ('motivo_mantenimiento', models.CharField(db_column='T069motivoMantenimiento', max_length=255)),
                ('observaciones', models.CharField(blank=True, db_column='T069observaciones', max_length=255, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, db_column='T069fechaSolicitud', null=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, db_column='T069fechaAnulacion', null=True)),
                ('justificacion_anulacion', models.CharField(blank=True, db_column='T069justificacionAnulacion', max_length=255, null=True)),
                ('ejecutado', models.BooleanField(db_column='T069ejecutado', default=False)),
                ('id_articulo', models.ForeignKey(db_column='T069Id_Articulo', on_delete=django.db.models.deletion.CASCADE, to='almacen.articulos')),
                ('id_persona_anula', models.ForeignKey(blank=True, db_column='T069Id_PersonaAnula', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_anula', to='seguridad.personas')),
                ('id_persona_solicita', models.ForeignKey(blank=True, db_column='T069Id_PersonaSolicita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_solicita', to='seguridad.personas')),
            ],
            options={
                'verbose_name': 'Programacion Mantenimientos',
                'verbose_name_plural': 'Programaciones Mantenimientos',
                'db_table': 'T069ProgramacionMantenimientos',
            },
        ),
        migrations.CreateModel(
            name='TiposActivo',
            fields=[
                ('cod_tipo_activo', models.CharField(db_column='T060CodTipoActivo', max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T060nombre', max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Activos',
                'verbose_name_plural': 'Tipos Activos',
                'db_table': 'T060TiposActivo',
            },
        ),
        migrations.CreateModel(
            name='TiposDepreciacionActivos',
            fields=[
                ('cod_tipo_depreciacion', models.AutoField(db_column='T059CodTipoDepreciacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='T059nombre', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Depreciacion Activos',
                'verbose_name_plural': 'Tipos Depreciacion Activos',
                'db_table': 'T059TiposDepreciacionActivos',
            },
        ),
        migrations.CreateModel(
            name='VehiculosArrendados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='estadosarticulo',
            name='cod_estado',
            field=models.CharField(db_column='T051Cod_Estado', max_length=1, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='magnitudes',
            name='cod_magnitud',
            field=models.AutoField(db_column='T054IdMagnitud', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organigramas',
            name='version',
            field=models.CharField(db_column='T017version', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadesmedida',
            name='id_magnitud',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Longitud'), (2, 'Volumen'), (3, 'Cantidad'), (4, 'Peso'), (5, 'Superficie'), (6, 'Temperatura'), (7, 'Tiempo')], db_column='T055Id_Magnitud'),
        ),
        migrations.CreateModel(
            name='RegistroMantenimientos',
            fields=[
                ('id_registro_mtto', models.AutoField(db_column='T070IdRegistroMtto', primary_key=True, serialize=False)),
                ('fecha_registrado', models.DateTimeField(db_column='T070fechaRegistrado')),
                ('fecha_ejecutado', models.DateTimeField(db_column='T070fechaEjecutado')),
                ('cod_tipo_mantenimiento', models.CharField(db_column='T070codTipoMantenimiento', max_length=1)),
                ('acciones_realizadas', models.TextField(blank=True, db_column='T070accionesRealizadas', null=True)),
                ('dias_empleados', models.SmallIntegerField(db_column='T070diasEmpleados')),
                ('observaciones', models.CharField(blank=True, db_column='T070observaciones', max_length=255, null=True)),
                ('fecha_estado_anterior', models.DateTimeField(blank=True, db_column='T070fechaEstadoAnterior', null=True)),
                ('valor_mantenimiento', models.IntegerField(blank=True, db_column='T070valorMantenimiento', null=True)),
                ('contrato_mantenimiento', models.CharField(blank=True, db_column='T070contratoMantenimiento', max_length=20, null=True)),
                ('ruta_documentos_soporte', models.CharField(blank=True, db_column='T070rutaDocumentosSoporte', max_length=255, null=True)),
                ('cod_estado_anterior', models.ForeignKey(blank=True, db_column='T070codEstadoAnterior', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.estadosarticulo')),
                ('cod_estado_final', models.ForeignKey(db_column='T070Cod_EstadoFinal', on_delete=django.db.models.deletion.CASCADE, related_name='cod_estado_final', to='almacen.articulos')),
                ('id_articulo', models.ForeignKey(db_column='T070d_Articulo', on_delete=django.db.models.deletion.CASCADE, related_name='id_articulo', to='almacen.articulos')),
                ('id_persona_diligencia', models.ForeignKey(db_column='T070Id_PersonaDiligencia', on_delete=django.db.models.deletion.CASCADE, related_name='id_persona_diligencia', to='seguridad.personas')),
                ('id_persona_realiza', models.ForeignKey(db_column='T070Id_PersonaRealiza', on_delete=django.db.models.deletion.CASCADE, related_name='id_persona_realiza', to='seguridad.personas')),
                ('id_programacion_mtto', models.ForeignKey(blank=True, db_column='T070Id_ProgramacionMtto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.programacionmantenimientos')),
            ],
            options={
                'verbose_name': 'Registro Mantenimientos',
                'verbose_name_plural': 'Registros Mantenimientos',
                'db_table': 'T070RegistroMantenimientos',
            },
        ),
        migrations.CreateModel(
            name='HojaDeVidaVehiculos',
            fields=[
                ('id_hoja_de_vida', models.AutoField(db_column='T066IdHojaDeVida', primary_key=True, serialize=False)),
                ('cod_tipo_vehiculo', models.CharField(blank=True, db_column='T066codTipoVehiculo', max_length=1, null=True)),
                ('tiene_platon', models.BooleanField(blank=True, db_column='T066tienePlaton', null=True)),
                ('capacidad_pasajeros', models.SmallIntegerField(blank=True, db_column='T066capacidadPasajeros', null=True)),
                ('color', models.CharField(blank=True, db_column='T066color', max_length=20, null=True)),
                ('linea', models.CharField(blank=True, db_column='T066linea', max_length=20, null=True)),
                ('tipo_combustible', models.CharField(blank=True, db_column='T066tipoCombustible', max_length=3, null=True)),
                ('es_arrendado', models.BooleanField(blank=True, db_column='T066esArrendado', null=True)),
                ('ultimo_kilometraje', models.IntegerField(blank=True, db_column='T066ultimoKilometraje', null=True)),
                ('fecha_ultimo_kilometraje', models.DateField(blank=True, db_column='T066fechaUltimoKilometraje', null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, db_column='T066fechaAdquisicion', null=True)),
                ('fecha_vigencia_garantia', models.DateField(blank=True, db_column='T066fechaVigenciaGarantia', null=True)),
                ('numero_motor', models.CharField(blank=True, db_column='T066numeroMotor', max_length=40, null=True)),
                ('numero_chasis', models.CharField(blank=True, db_column='T066numeroChasis', max_length=40, null=True)),
                ('cilindraje', models.SmallIntegerField(blank=True, db_column='T066cilindraje', null=True)),
                ('transmision', models.CharField(blank=True, db_column='T066transmision', max_length=20, null=True)),
                ('dimesion_llantas', models.SmallIntegerField(blank=True, db_column='T066dimensionLlantas', null=True)),
                ('capacidad_extintor', models.SmallIntegerField(blank=True, db_column='T066capacidadExtintor', null=True)),
                ('tarjeta_operacion', models.CharField(blank=True, db_column='T066tarjetaOperacion', max_length=20, null=True)),
                ('observaciones_adicionales', models.CharField(blank=True, db_column='T066observacionesAdicionales', max_length=255, null=True)),
                ('es_agendable', models.BooleanField(blank=True, db_column='T066esAgendable', null=True)),
                ('en_circulacion', models.BooleanField(blank=True, db_column='T066enCirculacion', null=True)),
                ('fecha_circulacion', models.DateField(blank=True, db_column='T066fechaCirculacion', null=True)),
                ('ruta_imagen_foto', models.CharField(blank=True, db_column='T066rutaImagenFoto', max_length=255, null=True)),
                ('id_articulo', models.ForeignKey(blank=True, db_column='T066Id_Articulo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.articulos')),
                ('id_proveedor', models.ForeignKey(blank=True, db_column='T066Id_Proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas')),
                ('id_vehiculo_arrendado', models.ForeignKey(blank=True, db_column='T066Id_VehiculoArrendado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='almacen.vehiculosarrendados')),
            ],
            options={
                'verbose_name': 'Hoja de vida vehiculos',
                'verbose_name_plural': 'Hojas de vida vehiculos',
                'db_table': 'T066HojaDeVidaVehiculos',
            },
        ),
        migrations.CreateModel(
            name='HojaDeVidaOtrosctivos',
            fields=[
                ('id_hoja_de_vida', models.AutoField(db_column='T067IdHojaDeVida', primary_key=True, serialize=False)),
                ('caracteristicas_fisicas', models.TextField(blank=True, db_column='T067caracteristicasFisicas', null=True)),
                ('especificaciones_tecnicas', models.TextField(blank=True, db_column='T067especificacionesTecnicas', null=True)),
                ('observaciones_adicionales', models.CharField(blank=True, db_column='T067observacionesAdicionales', max_length=255, null=True)),
                ('ruta_imagen_foto', models.CharField(blank=True, db_column='T067rutaImagenFoto', max_length=255, null=True)),
                ('id_articulo', models.ForeignKey(db_column='T067Id_Articulo', on_delete=django.db.models.deletion.CASCADE, to='almacen.articulos')),
            ],
            options={
                'verbose_name': 'Hoja de vida otros activos',
                'verbose_name_plural': 'Hojas de vida otros activos',
                'db_table': 'T065HojaDeVidaOtrosctivos',
            },
        ),
        migrations.CreateModel(
            name='HojaDeVidaComputadores',
            fields=[
                ('id_hoja_de_vida', models.AutoField(db_column='T065IdHojaDeVida', primary_key=True, serialize=False)),
                ('sistema_operativo', models.CharField(blank=True, db_column='T065sistemaOperativo', max_length=40, null=True)),
                ('suite_ofimatica', models.CharField(blank=True, db_column='T065suiteOfimatica', max_length=40, null=True)),
                ('antivirus', models.CharField(blank=True, db_column='T065antivirus', max_length=40, null=True)),
                ('color', models.CharField(blank=True, db_column='T065color', max_length=20, null=True)),
                ('tipo_de_equipo', models.CharField(blank=True, db_column='T065tipoDeEquipo', max_length=20, null=True)),
                ('tipo_almacenamiento', models.CharField(blank=True, db_column='T065tipoAlmacenamiento', max_length=30, null=True)),
                ('capacidad_almacenamiento', models.CharField(blank=True, db_column='T065capacidadAlmacenamiento', max_length=20, null=True)),
                ('procesador', models.CharField(blank=True, db_column='T065procesador', max_length=20, null=True)),
                ('memoria_ram', models.SmallIntegerField(blank=True, db_column='T065memoriaRAM', null=True)),
                ('observaciones_adicionales', models.CharField(blank=True, db_column='T065observacionesAdicionales', max_length=255, null=True)),
                ('otras_aplicaciones', models.CharField(blank=True, db_column='T065otrasAplicaciones', max_length=255, null=True)),
                ('ruta_imagen_foto', models.CharField(blank=True, db_column='T065rutaImagenFoto', max_length=255, null=True)),
                ('id_articulo', models.ForeignKey(db_column='T065Id_Articulo', on_delete=django.db.models.deletion.CASCADE, to='almacen.articulos')),
            ],
            options={
                'verbose_name': 'Hoja de vida computadores',
                'verbose_name_plural': 'Hojas de vida computadores',
                'db_table': 'T065HojaDeVidaComputadores',
            },
        ),
        migrations.CreateModel(
            name='DocumentosVehiculo',
            fields=[
                ('id_documentos_vehiculos', models.AutoField(db_column='T068IdDocumentosVehiculos', primary_key=True, serialize=False)),
                ('cod_tipo_documento', models.CharField(db_column='T068codTipoDocumento', max_length=4)),
                ('nro_documento', models.CharField(db_column='T068nroDocumento', max_length=20)),
                ('fecha_inicio_vigencia', models.DateField(db_column='T068fechaInicioVigencia')),
                ('fecha_expiracion', models.DateField(db_column='T068fechaExpiracion')),
                ('id_articulo', models.ForeignKey(db_column='T068Id_Articulo', on_delete=django.db.models.deletion.CASCADE, to='almacen.articulos')),
                ('id_empresa_proveedora', models.ForeignKey(blank=True, db_column='T068Id_EmpresaProveedora', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguridad.personas')),
            ],
            options={
                'verbose_name': 'Documento Vehiculo',
                'verbose_name_plural': 'Documentos Vehiculo',
                'db_table': 'T068DocumentosVehiculo',
                'unique_together': {('id_articulo', 'cod_tipo_documento', 'nro_documento')},
            },
        ),
    ]
