# Generated by Django 4.1.1 on 2022-11-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_alter_organigramas_ruta_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadrosclasificaciondocumental',
            name='ruta_soporte',
            field=models.FileField(blank=True, db_column='T206rutaSoporte', null=True, upload_to=''),
        ),
    ]
