# Generated by Django 4.1.1 on 2022-11-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_articulos_metodosvaloracionarticulos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.RemoveField(
            model_name='articulos',
            name='id',
        ),
        migrations.AddField(
            model_name='articulos',
            name='cod_estado_final',
            field=models.CharField(db_column='T057cod_estado_final', default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='id_articulo',
            field=models.AutoField(db_column='T057Id_Articulo', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='nombre',
            field=models.CharField(db_column='T057nombre', default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registromantenimientos',
            name='cod_estado_final',
            field=models.ForeignKey(db_column='T070Cod_EstadoFinal', on_delete=django.db.models.deletion.CASCADE, related_name='cod_estado_final_Registro', to='almacen.articulos'),
        ),
        migrations.AlterField(
            model_name='registromantenimientos',
            name='id_articulo',
            field=models.ForeignKey(db_column='T070d_Articulo', on_delete=django.db.models.deletion.CASCADE, related_name='id_articulo_Registro', to='almacen.articulos'),
        ),
        migrations.AlterModelTable(
            name='articulos',
            table='T057Articulos',
        ),
    ]
