# Generated by Django 4.1.1 on 2022-11-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_rename_unidades_organizacional_unidadesorganizacionales_id_unidad_organizacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivelesorganigrama',
            name='nombre',
            field=models.CharField(db_column='T018nombre', max_length=50),
        ),
        migrations.AlterField(
            model_name='nivelesorganigrama',
            name='orden_nivel',
            field=models.SmallIntegerField(db_column='T018ordenDelNivel'),
        ),
    ]
