# Generated by Django 4.1.1 on 2022-11-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_alter_nivelesorganigrama_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organigramas',
            name='fecha_terminado',
            field=models.DateTimeField(blank=True, db_column='T017fechaTerminado', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='nivelesorganigrama',
            unique_together={('id_organigrama', 'orden_nivel')},
        ),
    ]
